// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACu1D2aD2KmCCyUZ0S4ShzZ9k4Y_4qd7Q',
    appId: '1:87588654974:web:6d867d4cfa42d0f16c6d2f',
    messagingSenderId: '87588654974',
    projectId: 'bpm-bank',
    authDomain: 'bpm-bank.firebaseapp.com',
    storageBucket: 'bpm-bank.firebasestorage.app',
    measurementId: 'G-PYH09ZQZZB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBewQbQrHBziquPB07Vub8zLzEGrVmCsx8',
    appId: '1:87588654974:android:194c081762e971f46c6d2f',
    messagingSenderId: '87588654974',
    projectId: 'bpm-bank',
    storageBucket: 'bpm-bank.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeBSO5OdSMPcTrdK4VjR1RyHRl6rUEfkk',
    appId: '1:87588654974:ios:dd3baac66e15c5e26c6d2f',
    messagingSenderId: '87588654974',
    projectId: 'bpm-bank',
    storageBucket: 'bpm-bank.firebasestorage.app',
    iosBundleId: 'com.example.bpmBank',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeBSO5OdSMPcTrdK4VjR1RyHRl6rUEfkk',
    appId: '1:87588654974:ios:dd3baac66e15c5e26c6d2f',
    messagingSenderId: '87588654974',
    projectId: 'bpm-bank',
    storageBucket: 'bpm-bank.firebasestorage.app',
    iosBundleId: 'com.example.bpmBank',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACu1D2aD2KmCCyUZ0S4ShzZ9k4Y_4qd7Q',
    appId: '1:87588654974:web:d7f9bfd0037a78516c6d2f',
    messagingSenderId: '87588654974',
    projectId: 'bpm-bank',
    authDomain: 'bpm-bank.firebaseapp.com',
    storageBucket: 'bpm-bank.firebasestorage.app',
    measurementId: 'G-1XNNXBFYH1',
  );
}
